- Sources/SwiftCentrifuge/Client.swift
> Fix unlock issue

- .travis.yml
- Package.resolved
- Package.swift
- README.md
> Add SPM product (library) and update dependencies

- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Subscription.swift
write now I have a very weird situation:
A lot of awaiting threads
[screen](https://ibb.co/QMYDzZX)
> rewrite code to escape await logic

- CHANGELOG.md
- README.md
- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Types.swift
- SwiftCentrifuge.podspec
> make necessary fields public in public structs

- Sources/SwiftCentrifuge/Client.swift
Add initial WebSocket reconnection delay.
Mitigating issues with Starscream 3 connect timeout:
https://github.com/daltoniam/Starscream/issues/542
> Add initial WebSocket reconnection delay 

- Example/SwiftCentrifuge/ViewController.swift
- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Delegate.swift
- Sources/SwiftCentrifuge/Helpers.swift
- Sources/SwiftCentrifuge/Subscription.swift
- Sources/SwiftCentrifuge/Types.swift
- Sources/SwiftCentrifuge/client.pb.swift
- client.proto
> Server-side subscriptions

- CHANGELOG.md
- Example/SwiftCentrifuge/ViewController.swift
- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Helpers.swift
- Sources/SwiftCentrifuge/Subscription.swift
- Sources/SwiftCentrifuge/Types.swift
- Sources/SwiftCentrifuge/client.pb.swift
- client.proto
In preparation for Centrifugo v3 and Centrifuge v0.18.0
> Adapt to latest protocol

- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Subscription.swift
> Use client queue for subscription ops

- CHANGELOG.md
- Sources/SwiftCentrifuge/WebSocket.swift
> Avoid auto Origin

- Sources/SwiftCentrifuge/Client.swift
More information in https://github.com/centrifugal/centrifuge-swift/issues/61
> Fix possible crash in handleAsyncData

- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Delegate.swift
spec: [connect-result-fields](https://centrifugal.dev/docs/server/proxy#connect-result-fields)
> added data filed to CentrifugeConnectEvent

- Sources/SwiftCentrifuge/Client.swift
> Fix token fetching before connecting to the server

- Example/SwiftCentrifuge.xcodeproj/project.pbxproj
- Example/SwiftCentrifuge/PrintLogger.swift
- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Logger.swift
- Sources/SwiftCentrifuge/Subscription.swift
Added minimal logging interface and "trace" level events for WebSocket.
> Add centrifuge logger interface

- .github/workflows/ci.yml
> Fix CI: outdated macos image

- Sources/SwiftCentrifuge/Subscription.swift
This PR fixes "unsubscription" issues during `removeSubscription` call. 
Steps to reproduce the issues:
1. Connect to a server
2. Subscribe to channel
3. Remove the subscription using `client.removeSubscription` and immediately nullify your reference to the subscription
The `async` block inside `processUnsubscribe` might not witness a strong ref to the subscription object.
> Fix missing "unsubscribe" server request

- Example/SwiftCentrifuge.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Sources/SwiftCentrifuge/Client.swift
- Sources/SwiftCentrifuge/Subscription.swift
- Sources/SwiftCentrifuge/client.pb.swift
- client.proto
Companion for https://github.com/centrifugal/centrifuge-js/pull/223
> getToken refactoring

- CHANGELOG.md
- SwiftCentrifuge.podspec
> Prepare 0.6.0

- Sources/SwiftCentrifuge/Delegate.swift
Update protection level to public
> Update protection level

- Sources/SwiftCentrifuge/WebSocket/NativeWebSocket.swift
> fix: add @unknown default to URLSessionTask.State ext switch

- SwiftCentrifuge.podspec
> Bump lib version to 0.8.2
